### ISSUE TITLE
Вынести литералы в константы

### ISSUE THREAD

**Issue by invasy** [foss-news/fossnewsbot#5]
- Текстовые сообщения для пользователя:
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L30-L33
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L40-L42
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L100
- Статус статей:
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L58
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L60
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L62
- Формат даты и времени:
  - https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L66

**Comment by lemonbro627** [comment]
сообщения вынесены в константы
статусы вынесены в константы
дата и время вынесены в fngsapi.py
