### ISSUE TITLE
Выделить api-запросы в отдельные методы

### ISSUE THREAD

**Issue by invasy** [foss-news/fossnewsbot#7]
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L106
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L114
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L117
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L131
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L135
- https://github.com/foss-news/fossnewsbot/blob/ded9d61502d7e141e7b6ad3ba0123207c22e4197/main.py#L139

**Comment by lemonbro627** [comment]
выведены в fngsapi.py
